### ISSUE TITLE
Usage / Progress?

### ISSUE THREAD

**Issue by n8sabes** [waynevanson/react-sortablejs-typescript#1]
Hi Wayne,

Thank you for taking this on -- very desirable and needed for anybody who actually cares about their React TypeScript project/code quality.

I am not sure where your progress is, but I'm hankering to use your module. Is it usable in any form yet, and if so, can you provide any instructions for integrating it into a CRA-Typescript project?

Thank you, again!

**Comment by waynevanson** [comment]
Check it out now, I've got it ready to use for the most part.

Instructions are in the read me.

**Comment by waynevanson** [comment]
Hold on a sec, I'm going to upload this as a package so iut can be downloaded with `yarn add react-sortablejs-typescript`

**Comment by waynevanson** [comment]
@n8sabes You should just be able to `yarn add react-sortablejs-typescript` into your project and it should work. The readme has basic examples and am happy to help out wherever you have an issue; this is a chance to add great documentation!
